# Generated by Django 4.0.6 on 2022-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
