# Generated by Django 4.0.6 on 2022-07-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_date_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
